# 练习解答 {#sec-exercise-solutions}

\addtocontents{toc}{\protect\setcounter{tocdepth}{0}}

```{r}
#| include: false
source("_common.R")
```



## 第 1 章 {#sec-exercise-solutions-01 .unlisted}

::: exercises-solution

{{< include exercises/_01-sa-data-hello.qmd >}}

:::

## 第 2 章 {#sec-exercise-solutions-02 .unlisted}

::: exercises-solution

{{< include exercises/_02-sa-data-design.qmd >}}

:::

## 第 3 章 {#sec-exercise-solutions-03 .unlisted}

应用章节，无练习。

## 第 4 章 {#sec-exercise-solutions-04 .unlisted}

::: exercises-solution

{{< include exercises/_04-sa-explore-categorical.qmd >}}

:::

## 第 5 章 {#sec-exercise-solutions-05 .unlisted}

::: exercises-solution

{{< include exercises/_05-sa-explore-numerical.qmd >}}

:::

## 第 6 章 {#sec-exercise-solutions-06 .unlisted}

应用章节，无练习。

## 第 7 章 {#sec-exercise-solutions-07 .unlisted}

::: exercises-solution

{{< include exercises/_07-sa-model-slr.qmd >}}

:::

## 第 8 章 {#sec-exercise-solutions-08 .unlisted}

::: exercises-solution

{{< include exercises/_08-sa-model-mlr.qmd >}}

:::

## 第 9 章 {#sec-exercise-solutions-09 .unlisted}

::: exercises-solution

{{< include exercises/_09-sa-model-logistic.qmd >}}

:::

## 第 10 章 {#sec-exercise-solutions-10 .unlisted}

应用章节，无练习。

## 第 11 章 {#sec-exercise-solutions-11 .unlisted}

::: exercises-solution

{{< include exercises/_11-sa-foundations-randomization.qmd >}}

:::

## 第 12 章 {#sec-exercise-solutions-12 .unlisted}

::: exercises-solution

{{< include exercises/_12-sa-foundations-bootstrapping.qmd >}}

:::

## 第 13 章 {#sec-exercise-solutions-13 .unlisted}

::: exercises-solution

{{< include exercises/_13-sa-foundations-mathematical.qmd >}}

:::

## 第 14 章 {#sec-exercise-solutions-14 .unlisted}

::: exercises-solution

{{< include exercises/_14-sa-foundations-errors.qmd >}}

:::

## 第 15 章 {#sec-exercise-solutions-15 .unlisted}

应用章节，无练习。

## 第 16 章 {#sec-exercise-solutions-16 .unlisted}

::: exercises-solution

{{< include exercises/_16-sa-inference-one-prop.qmd >}}

:::

## 第 17 章 {#sec-exercise-solutions-17 .unlisted}

::: exercises-solution

{{< include exercises/_17-sa-inference-two-props.qmd >}}

:::

## 第 18 章 {#sec-exercise-solutions-18 .unlisted}

::: exercises-solution

{{< include exercises/_18-sa-inference-tables.qmd >}}

:::

## 第 19 章 {#sec-exercise-solutions-19 .unlisted}

::: exercises-solution

{{< include exercises/_19-sa-inference-one-mean.qmd >}}

:::

## 第 20 章 {#sec-exercise-solutions-20 .unlisted}

::: exercises-solution

{{< include exercises/_20-sa-inference-two-means.qmd >}}

:::

## 第 21 章 {#sec-exercise-solutions-21 .unlisted}

::: exercises-solution

{{< include exercises/_21-sa-inference-paired-means.qmd >}}

:::

## 第 22 章 {#sec-exercise-solutions-22 .unlisted}

::: exercises-solution

{{< include exercises/_22-sa-inference-many-means.qmd >}}

:::

## 第 23 章 {#sec-exercise-solutions-23 .unlisted}

应用章节，无练习。

## 第 24 章 {#sec-exercise-solutions-24 .unlisted}

::: exercises-solution

{{< include exercises/_24-sa-inf-model-slr.qmd >}}

:::

## 第 25 章 {#sec-exercise-solutions-25 .unlisted}

::: exercises-solution

{{< include exercises/_25-sa-inf-model-mlr.qmd >}}

:::

## 第 26 章 {#sec-exercise-solutions-26 .unlisted}

::: exercises-solution

{{< include exercises/_26-sa-inf-model-logistic.qmd >}}

:::