# 前言 {.unnumbered}

\vspace{-10mm}

欢迎阅读《现代统计学导论》第二版！

我们希望读者在建立统计思维和方法基础的同时，还能从本书中领会以下三个理念：

1.  统计学是一门应用学科，具有广泛的实际应用。
2.  你无需成为数学高手，也能从有趣的真实数据中学习。
3.  数据通常是杂乱的，统计工具也不完美。然而，一旦你理解了这些工具的优缺点，就能利用它们来发现关于世界的有趣事物。

## 教材概述 {.unnumbered .unlisted}

-   **第一部分：数据导论。** 数据结构、变量、汇总、图形，以及基本的数据收集与研究设计技术。
-   **第二部分：探索性数据分析。** 数据可视化与汇总，特别强调多变量间的关系。
-   **第三部分：回归建模。** 使用线性回归和逻辑斯谛回归对数值和分类结果变量进行建模，并利用模型结果描述关系和进行预测。
-   **第四部分：推断基础。** 通过案例研究引入统计推断的思想，涵盖随机化检验、自助法区间和数学模型。
-   **第五部分：统计推断。** 使用随机化检验、自助法区间以及针对数值和分类数据的数学模型，进一步深入探讨统计推断的细节。
-   **第六部分：推断建模。** 将目前所学的推断技术扩展到线性回归和逻辑斯谛回归场景，并评估模型性能。

每个部分包含多个章节，并以一个案例研究结尾。
案例研究基于该部分涵盖的内容，运用该部分的工具和技术，提供一个高层次的概览。

在涵盖统计推断的章节中，我们采用了一种并行结构，引导学生了解每个推断主题的计算方法和数学方法。
试图涵盖每个主题的所有方法，对于一学期的课程来说内容可能过多。
我们建议您在引导学生学习本书时做出慎重选择。
以下是几种可能的学习路径（括号内为章节编号）：

* 聚焦**计算方法与数学方法的并行结构**：数据导论 (1, 2)，探索性数据分析 (4, 5)，回归 (7)，推断基础 (11, 12, 13, 14)，推断 (16, 17, 18, 19, 20, 21, 22 的子集；可能的选择: 16, 17, 19, 20)。
* 聚焦**计算方法**：数据导论 (1, 2)，探索性数据分析 (4, 5)，回归 (7)，推断基础 (11, 12, 14)，推断 (仅包含计算方法，从 16, 17, 18, 19, 20, 21, 22 中选择子集)。
* 聚焦**数学方法**：数据导论 (1, 2)，探索性数据分析 (4, 5)，回归 (7)，推断基础 (11, 12, 13, 14)，推断 (仅包含数学方法，从 16, 17, 18, 19, 20, 21, 22 中选择子集)。
* 聚焦**建模**：数据导论 (1, 2)，探索性数据分析 (4, 5)，回归 (7, 8, 9)，推断基础 (11, 12, 13, 14)，推断 (19)，推断建模 (24, 25, 26)。

我们预计，大多数遵循经典教学大纲的课程都没有时间涵盖最后一部分“推断建模”（第24、25、26章）的内容。

\clearpage

每章以复习结尾，包含章节小结以及本章引入的关键术语列表。
如果您不确定其中某些术语的含义，我们建议您返回正文复习它们的定义。
我们有意按字母顺序而非出现顺序呈现它们，这样定位起来会稍具挑战性。
不过，您应该能很容易地认出它们，因为它们以**粗体**显示。

## 第二版的变化 {.unnumbered .unlisted}

虽然第二版相对于[第一版](https://openintro-ims1.netlify.app/)没有重大变动，但我们努力改进了内容，增加了练习，并更新了文本和代码以反映最佳实践的变化（例如，本书现在使用 [Quarto](https://quarto.org/) 编写）。

最大的变动简要总结如下：

* 增加了 25 个全新的练习。大多数新练习被附加在现有练习之后，以便在不同版本间保持相似的编号。然而，为了在同一主题下同时提供奇数练习（附有解答）和偶数练习（不附解答），少数练习被移动了位置。

* 多个数据集被添加或更新。例如，关于 2022 年北卡罗来纳州达勒姆市空气质量的 [`pm25_2022_durham`](http://openintrostat.github.io/openintro/reference/pm25_2022_durham.html) 数据可以在 [**openintro**](https://openintrostat.github.io/openintro/) R 包中找到。

* [第 -@sec-data-applications 章]进行了重写，更新了背景和数据示例。此外，在 [第 -@sec-data-applications 章]中，我们探讨了 Simpson（辛普森）悖论。

* 在全书的正文和练习中，“statistically significant”（统计显著的）已被改为“statistically discernible”（统计上可辨识的），以便与“significant”一词更口语化的用法保持距离。

## 示例与练习 {.unnumbered .unlisted}

提供示例是为了帮助读者理解如何应用相关方法。

::: {.workedexample data-latex=""}
这是一个示例。
当此处提出问题时，可以在哪里找到答案？

------------------------------------------------------------------------

答案可以在这里找到，就在示例的解答部分！
:::

当我们认为读者准备好尝试自己确定解决方案时，会将其设计为“指导练习”（Guided Practice）。

::: {.guidedpractice data-latex=""}
读者可以通过查看脚注中的完整解答，来核对或学习任何“指导练习”的答案。[^preface-1]
:::

[^preface-1]: “指导练习”旨在拓展您的思维，您可以通过查看任何“指导练习”的脚注解答来自我检查。

每章末尾也提供了练习。
奇数编号练习的解答在 [附录 -@sec-exercise-solutions]中给出。

\clearpage

## 数据集及其来源 {.unnumbered .unlisted}

本书中使用的大部分数据集都可以在各种 R 包中找到。
每次在正文中引入新数据集时，都会提供类似如下的包引用。
其中许多数据集都在 [**openintro**](http://openintrostat.github.io/openintro) R 包中，该包包含了 [OpenIntro](https://www.openintro.org/) 开源教材中使用的数据集。[^preface-2]

[^preface-2]: Mine Çetinkaya-Rundel and David Diez and Andrew Bray and Albert Y. Kim and Ben Baumer and Chester Ismay and Nick Paterno and Christopher Barr (2024).
    openintro: Datasets and Supplemental Functions from 'OpenIntro' Textbooks and Labs.
    R package version 2.5.0.
    <https://github.com/openintrostat/openintro>.

::: {.data data-latex=""}
[`textbooks`](http://openintrostat.github.io/openintro/reference/textbooks.html) 数据可以在 [**openintro**](http://openintrostat.github.io/openintro) R 包中找到。
:::

全书使用的数据集均来自民意调查和科学文章等真实来源，只有在少数情况下我们会使用玩具数据（toy data）来突出某个特定特征或解释某个特定概念。
真实数据的来源参考信息在书末提供。

## 使用 R 进行计算 {.unnumbered .unlisted}

本书的正文和练习不依赖于特定的计算语言，然而，虽然不借助计算也能学习现代统计学，但无法将其应用。
因此，我们建议您利用每部分末尾提供的交互式 R 教程和 R 实验，来实践在各部分中学到的概念。

### 交互式 R 教程 {.unnumbered .unlisted}

这些自定进度的交互式 R 教程是使用 [learnr](https://rstudio.github.io/learnr/index.html) R 包开发的，只需一个网络浏览器即可完成。

::: {.alltutorials data-latex=""}
每部分附带一个包含 4-10 课的教程，并像这样列出。
:::

::: {.singletutorial data-latex=""}
每一课像这样列出。
:::

::: {.content-visible when-format="pdf"}
您可以访问 <https://openintrostat.github.io/ims-tutorials> 获取支持本书的完整教程列表。
:::

::: {.content-visible when-format="html"}
您可以访问[此处](https://openintrostat.github.io/ims-tutorials)获取支持本书的完整教程列表。
:::

### R 实验 {.unnumbered .unlisted}

一旦您对教程中的内容感到得心应手，我们也鼓励您通过每部分末尾链接的计算实验来应用所学。
这些实验由数据分析案例研究组成，需要使用 [R](https://cran.r-project.org/) 和 [RStudio](https://posit.co/products/open-source/rstudio/)。
第一个实验包含安装说明。
如果您不想在本地安装软件，也可以免费试用 [Posit Cloud](https://posit.cloud/)。

::: {.singlelab data-latex=""}
每部分的实验像这样列出。
:::

::: {.content-hidden unless-format="pdf"}
你可以在 [openintro.org/go?id=ims-r-labs](https://www.openintro.org/go?id=ims-r-labs) 访问支持本书的完整实验列表。
:::

::: {.content-visible when-format="html"}
你可以通过[此链接](https://www.openintro.org/go?id=ims-r-labs)访问支持本书的完整实验列表。
:::

\clearpage

## OpenIntro，在线资源与参与方式 {.unnumbered .unlisted}

OpenIntro 是一个致力于开发免费和平价的教育资料的组织。我们鼓励所有学习或教授统计学的人访问 [openintro.org](http://www.openintro.org) 并参与其中。

所有 OpenIntro 资源都是免费的，无论是否以本书为配套教材，任何人都欢迎使用这些在线工具与资源。

我们重视您的反馈。
如果您特别喜欢项目的某一部分，或认为某部分需要改进，我们期待您的反馈。
对于本书的具体反馈，您可以在本书的 GitHub 仓库提交 issue，地址是 [github.com/openintrostat/ims](https://github.com/openintrostat/ims)。
您也可以通过我们在 [openintro.org](https://www.openintro.org/form/?f=contact) 的联系表单，提供关于本书或任何其他 OpenIntro 资源的反馈。

## 致谢 {.unnumbered .unlisted}

如果没有所有参与者的奉献和志愿付出，*OpenIntro* 项目就不可能实现。我们希望您能和我们一起，向所有为 OpenIntro 贡献力量的志愿者们致以由衷的*感谢*。

作者要感谢以下各位：

-   David Diez 和 Christopher Barr，感谢他们为本书第 1 版所做的工作，
-   Ben Baumer 和 Andrew Bray，感谢他们重新思考我们呈现这些材料的方式与顺序，并作为互动式教程内容的原作者所做的贡献，
-   Yanina Bellini Saibene、Florencia D'Andrea 和 Roxana Noelia Villafañe，感谢他们在创建 learnr 互动式教程方面的工作，
-   Peter Baumgartner，感谢他对互动式 learnr 教程的审阅和修订，
-   Will Gray，感谢其概念图设计，
-   Allison Theobold、Melinda Yager 和 Randy Prium，感谢他们对本书提供的宝贵反馈和审阅，
-   Colin Rundel，感谢他对内容的反馈以及在从 LaTeX 转换到 R Markdown 方面提供的技术帮助，
-   Christophe Dervieux，感谢他在解决多格式输出 bookdown 问题上的帮助，以及
-   Müge Çetinkaya 和 Meenal Patel，感谢他们的设计理念。

我们还要感谢使得本书的开发和创作成为可能的开源工具的开发者们，例如 [Quarto](https://quarto.org/)、[tidyverse](https://tidyverse.org/)、[tidymodels](https://tidymodels.org/) 和 [icons8](http://icons8.com/)。

我们也感谢众多通过反馈帮助改进 OpenIntro 资源的教师、学生和其他读者。
