{
  "hash": "8779d7b6c1ee6677d7698ae123861888",
  "result": {
    "engine": "knitr",
    "markdown": "# 使用数学模型进行推断 {#sec-foundations-mathematical}\n\n\n\n\n\n\n\n\n::: {.chapterintro data-latex=\"\"}\n在 [第 -@sec-foundations-randomization 章]和 [第 -@sec-foundations-bootstrapping 章]中，我们利用计算技术探讨了关于总体参数的问题。对于随机化检验，我们在假设原假设成立的前提下对数据进行置换。对于自助法，我们通过对数据进行重抽样来衡量变异性。在许多情况下（对于样本比例确实如此），统计量的变异性既可以通过计算方法（如前几章那样）来描述，也可以通过数学公式（如本章这样）来描述。\n\n这里介绍正态分布，是为了描述从重复样本或重复实验中得到的样本比例的变异性。正态分布非常强大，因为它可以描述许多不同统计量的变异性，在本书的后续内容中我们还会不断遇到正态分布。\n\n不过，目前我们的重点在于这两条途径的相似之处：即数据如何分别通过计算方法或数学模型为研究问题提供洞见。\n:::\n\n## 中心极限定理 {#sec-CLTsection}\n\n在前几章中，我们遇到了四个案例研究。虽然它们的研究背景、结果以及分析数据的方法各不相同，但它们都有一个共同点：统计量的分布（称为**抽样分布**）具有相似的大致形状。\\index{sampling distribution} 你可能已经注意到这些分布都是对称且呈钟形的。\n\n\n\n\n\n\n::: {.important data-latex=\"\"}\n**抽样分布。**\n\n抽样分布是指从给定总体中抽取给定样本量的所有可能样本，其*样本统计量*所有可能值的分布。我们可以将抽样分布理解为描述样本统计量（例如样本比例 $\\hat{p}$ 或样本均值 $\\bar{x}$）在不同研究之间是如何变化的。与抽样分布相对的是数据分布，后者展示的是*观测到的*数据值的变异性。数据分布可以从观测值本身直接进行可视化。然而，由于抽样分布描述的是基于多项研究计算出的样本统计量，因此无法直接从单个数据集进行可视化。相反，我们使用计算方法或数学模型来估计抽样分布，从而描述样本统计量在重复研究中的预期变异性。\n:::\n\n[图 -@fig-FourCaseStudies]展示了我们运行 10,000 次模拟后，四个案例研究中每一个的原假设分布。请注意，**原假设分布**\\index{null distribution}是在原假设为真的设定下所创建的统计量的抽样分布。因此，原假设分布的中心将总是位于原假设所给出的参数值上。对于最初只有 1,000 次模拟的机会成本研究，我们已经额外补充了 9,000 次模拟。\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![前文介绍的四个案例研究的原假设分布。\n注意，每个分布的中心由原假设中设定的参数值给出。\n](foundations-mathematical_files/figure-pdf/fig-FourCaseStudies-1.png){#fig-FourCaseStudies fig-alt='本书中四个示例（机会成本、性别歧视、医疗顾问、击节者与听者）的原假设分布直方图。\n每个直方图的中心分别位于原假设的比例值 0, 0, 0.1 和 0.5。\n' width=80%}\n:::\n:::\n\n\n\n::: {.guidedpractice data-latex=\"\"}\n描述这些分布的形态，并指出任何你认为有趣的地方。[^13-foundations-mathematical-1]\n:::\n\n[^13-foundations-mathematical-1]: 总体而言，这些分布相当对称。医疗顾问案例是唯一具有明显偏态（右偏）的分布。\n\n医疗顾问案例是唯一具有明显偏态的分布。\n正如我们在 [第 -@sec-data-hello 章]中观察到的，分布常常是偏态的或包含离群值。\n然而，到目前为止，我们遇到的原假设分布看起来都有些相似，且绝大部分是对称的。\n它们都类似于钟形曲线。\n这种钟形曲线的相似性并非偶然，而是由数学理论保证的。\n\n::: {.important data-latex=\"\"}\n**比例的中心极限定理。**\\index{Central Limit Theorem}\n\n如果我们考察一个比例（或比例差），且该场景满足某些条件，那么样本比例（或比例差）将表现为服从一条称为*正态分布*的钟形曲线。\n:::\n\n\n\n\n\n一个完美的正态分布示例如 [图 -@fig-simpleNormal]所示。\n想象一下，将一条正态曲线叠加在 [图 -@fig-FourCaseStudies]的四个原假设分布之上。\n虽然每个图的均值（中心）和标准差（宽度或展布）可能不同，但大致形状基本保持不变。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![一条正态曲线。](foundations-mathematical_files/figure-pdf/fig-simpleNormal-1.png){#fig-simpleNormal fig-alt='一条均值为0、标准差为1的正态曲线。' width=60%}\n:::\n:::\n\n\n\n\n数学理论保证，在满足特定条件时，如果进行重复抽样，样本比例或样本比例差将近似服从正态分布。\n（注意：我们通常只抽取**一个**样本，但数学模型能够让我们知道，*假设*我们重复抽样会得到什么结果。）这些条件可以分为两大类，分别描述了观测之间的独立性以及需要抽取足够大的样本量。\n\n1.  样本中的观测相互**独立**。\n    如果我们从总体中进行随机抽样，就可以保证独立性。\n    如果我们随机将个体分配到处理组和对照组，也可以保证独立性。\n\n2.  样本**足够大**。\n    样本量不能太小。\n    “小”的标准因情境而异，我们将在 [第 -@sec-inference-one-prop 章]中为比例提供合适的指导原则。\n\n到目前为止，我们还没有用到正态分布。\n我们一直能够使用模拟技术相对容易地解答问题。\n然而，情况很快会改变。\n模拟数据可能并不简单。\n例如，在 [第 -@sec-model-mlr 章]中我们介绍包含多个预测变量的回归模型时遇到的一些场景，就需要复杂的模拟才能得出推断结论。\n相比之下，正态分布及与之类似的其他分布，为统计推断提供了一个适用范围极广的通用框架。\n\n::: {.important data-latex=\"\"}\n**技术条件。**\n\n想要用正态近似来描述样本比例在不同样本间的抽样分布，必须满足两个条件。\n如果这些条件不成立，那么使用正态分布（以及与之相关的概念，如 z 统计量、从正态曲线得出的概率等）进行推断分析是不明智的。\n\n1.  **独立观测**\n2.  **样本足够大：** 对于比例，样本中期望成功数和期望失败数均至少为 10。\n:::\n\n## 正态分布 {#sec-normalDist}\n\n在我们统计学中见到的所有分布里，有一种分布绝对是最常见的。\n这种对称、单峰的钟形曲线在统计学中无处不在。\n它如此常见，以至于人们用各种名称来称呼它，包括**正态曲线**\\index{normal curve}、**正态模型**\\index{normal model}或**正态分布**\\index{normal distribution}。[^13-foundations-mathematical-2]\n在一定条件下，样本比例、样本均值以及样本差可以使用正态分布建模。\n此外，某些变量，如 SAT 分数和美国成年男性的身高，也近似服从正态分布。\n\n[^13-foundations-mathematical-2]: 它也被称为高斯分布，得名于首位用数学表达式将其形式化的 Frederic Gauss（弗雷德里克·高斯）。\n\n\n\n\n\n\n::: {.important data-latex=\"\"}\n**正态分布事实。**\n\n许多变量的分布接近正态，但没有一个是完全正态的。\n因此，正态分布虽然对任何单个问题而言都不是完美的，但对各种各样的问题都非常有用。\n:::\n\n\\vspace{-2mm}\n\n在本节中，我们将结合数据来讨论正态分布，以熟悉正态分布的相关技术。\n在接下来的小节及后续内容中，我们将把讨论重点转向应用正态分布及其他相关分布，对假设检验和构建置信区间中的点估计进行建模。\n\n### 正态分布模型\n\n正态分布总是描述一条对称、单峰、钟形的曲线。\n然而，正态曲线的外观会因模型的具体细节而有所不同。\n具体来说，可以用两个参数来调整正态模型：均值和标准差。\n你可能已经猜到，改变均值会使钟形曲线向左或向右移动，而改变标准差则会拉伸或压缩曲线。\n[图 -@fig-twoSampleNormals-1]展示了均值为 $0$、标准差为 $1$ 的正态分布（这通常被称为**标准正态分布**\\index{standard normal distribution}）。\n右侧展示的是均值为 $19$、标准差为 $4$ 的正态分布。\n[图 -@fig-twoSampleNormalsStacked]展示了同样的两个正态模型，但绘制在相同尺度下。\n\n\\vspace{-3mm}\n\n\n::: {#fig-twoSampleNormals .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![均值 = 0，标准差 = 1](foundations-mathematical_files/figure-pdf/fig-twoSampleNormals-1.png){#fig-twoSampleNormals-1 fig-alt='两条正态曲线。第一条均值为零，标准差为一，称为标准正态分布。\n第二条均值为 19，标准差为四。\n' width=100%}\n:::\n\n::: {.cell-output-display}\n![均值 = 19，标准差 = 4](foundations-mathematical_files/figure-pdf/fig-twoSampleNormals-2.png){#fig-twoSampleNormals-2 fig-alt='两条正态曲线。第一条均值为零，标准差为一，称为标准正态分布。\n第二条均值为 19，标准差为四。\n' width=100%}\n:::\n\n两个中心和离散程度不同的正态分布。\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![展现在 [图 -@fig-twoSampleNormals]中的两个正态模型，但绘制在相同尺度下。\n](foundations-mathematical_files/figure-pdf/fig-twoSampleNormalsStacked-1.png){#fig-twoSampleNormalsStacked fig-alt='两条绘制在同一条坐标轴上的正态曲线。一条是\n均值为零、标准差为一的标准正态曲线。另一条\n均值为 19，标准差为四。\n' width=100%}\n:::\n:::\n\n\n\n\n\\clearpage\n\n如果一个正态分布的均值为 $\\mu$，标准差为 $\\sigma,$ 我们可以将该分布记作 $N(\\mu, \\sigma).$ [图 -@fig-twoSampleNormalsStacked]中的两个分布可以记作\n\n$$ N(\\mu = 0, \\sigma = 1)\\quad\\text{和}\\quad N(\\mu = 19, \\sigma = 4) $$\n\n因为均值和标准差能精确地描述一个正态分布，所以它们被称为该分布的**参数**\\index{parameter}。\n\n\n\n\n\n\n::: {.workedexample data-latex=\"\"}\n写出以下参数对应的正态分布的简写形式。\n\na.  均值 5 和标准差 3\nb.  均值 -100 和标准差 10\nc.  均值 2 和标准差 9\n\n------------------------------------------------------------------------\n\na.  $N(\\mu = 5,\\sigma = 3)$\nb.  $N(\\mu = -100, \\sigma = 10)$\nc.  $N(\\mu = 2, \\sigma = 9)$\n:::\n\n### 用 z 统计量进行标准化\n\n::: {.guidedpractice data-latex=\"\"}\nSAT 分数近似服从均值为 1500 分、标准差为 300 分的正态分布。\nACT 分数也近似服从均值为 21 分、标准差为 5 分的正态分布。\n假设 Nel 的 SAT 得了 1800 分，而 Sian 的 ACT 得了 24 分。\n谁的表现更好？[^13-foundations-mathematical-3]\n:::\n\n[^13-foundations-mathematical-3]: 我们以标准差作为衡量标准。\n    Nel 的 SAT 分数比平均数高出 1 个标准差：$1500 + 300 = 1800.$ Sian 的 ACT 分数比均值高出 0.6 个标准差：$21 + 0.6 \\times 5 = 24.$ 从 [图 -@fig-satActNormals]中我们可以看出，Nel 的表现相对于其他考生来说比 Sian 更出色，所以 Nel 的分数更好。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![在 SAT 和 ACT 分数分布上显示的 Nel 和 Sian 的分数。\n](foundations-mathematical_files/figure-pdf/fig-satActNormals-1.png){#fig-satActNormals fig-alt='Nel 的 SAT 分数绘制在均值为 1500、标准差为 300 的正态曲线上。\nSian 的 ACT 分数绘制在均值为 21、标准差为 5 的正态曲线上。\nNel 的分数相对高于 Sian 的分数。\n' width=80%}\n:::\n:::\n\n\n\n\n\\clearpage\n\n前一个示例的解决方案依赖于一种称为 z 统计量的标准化技术，这种方法最常用于近似正态分布的观测（但也可以用于任何分布）。\n一个观测的 **z 统计量**\\index{Z score} 定义为其落在均值之上或之下的标准差个数。\n如果一个观测高于均值一个标准差，则其 z 统计量为 1。\n如果它落在均值*之下* 1.5 个标准差，则其 z 统计量为 -1.5。\n如果 $x$ 是来自分布 $N(\\mu, \\sigma)$ 的一个观测，我们将 z 统计量数学定义为\n\n\n\n\n\n\n\n$$ Z = \\frac{x-\\mu}{\\sigma} $$\n\n利用 $\\mu_{SAT}=1500,$ $\\sigma_{SAT}=300,$ 和 $x_{Nel}=1800,$ 我们可以求出 Nel 的 z 统计量：\n\n$$ Z_{Nel} = \\frac{x_{Nel} - \\mu_{SAT}}{\\sigma_{SAT}} = \\frac{1800-1500}{300} = 1 $$\n\n::: {.important data-latex=\"\"}\n**z 统计量。**\n\n某个观测的 z 统计量是其落在均值之上或之下的标准差个数。\n我们使用以下公式计算观测 $x$ 的 z 统计量，其中 $x$ 服从均值为 $\\mu$、标准差为 $\\sigma$ 的分布：\n\n$$Z = \\frac{x-\\mu}{\\sigma}$$\n\n如果观测 $x$ 来自一个以 $\\mu$ 为中心、标准差为 $\\sigma$ 的*正态*分布，那么 z 统计量将服从一个中心为 0、标准差为 1 的*正态*分布。\n也就是说，在从 $x$ 转换到 $Z$ 时，虽然中心和离散程度都发生了偏移，但正态性得以保持。\n:::\n\n::: {.guidedpractice data-latex=\"\"}\n使用 Sian 的 ACT 分数 24，以及 ACT 均值和标准差来计算其 z 统计量。[^13-foundations-mathematical-4]\n:::\n\n[^13-foundations-mathematical-4]: $Z_{Sian} = \\frac{x_{Sian} - \\mu_{ACT}}{\\sigma_{ACT}} = \\frac{24 - 21}{5} = 0.6$\n\n高于均值的观测其 z 统计量总是为正，而低于均值的观测则为负。\n如果一个观测等于均值（例如，SAT 分数为 1500），那么其 z 统计量为 $0.$\n\n::: {.workedexample data-latex=\"\"}\n令 $X$ 表示一个来自 $N(\\mu=3, \\sigma=2),$ 的随机变量，并假设我们观测到 $x=5.19.$ 计算 $x$ 的 z 统计量。然后，利用该 z 统计量确定 $x$ 落在均值之上或之下多少个标准差。\n\n------------------------------------------------------------------------\n\n其 z 统计量由 $Z = \\frac{x-\\mu}{\\sigma} = \\frac{5.19 - 3}{2} = 2.19/2 = 1.095.$ 给出。观测 $x$ 在均值*之上* 1.095 个标准差。我们知道它一定在均值之上，因为 $Z$ 是正的。\n:::\n\n::: {.guidedpractice data-latex=\"\"}\n刷尾负鼠的头长服从一个近似正态分布，其均值为 92.6 mm，标准差为 3.6 mm。\n请计算头长分别为 95.4 mm 和 85.8 mm 的刷尾负鼠的 z 统计量。[^13-foundations-mathematical-5]\n:::\n\n[^13-foundations-mathematical-5]: 对于 $x_1=95.4$ mm：$Z_1 = \\frac{x_1 - \\mu}{\\sigma} = \\frac{95.4 - 92.6}{3.6} = 0.78.$ 对于 $x_2=85.8$ mm：$Z_2 = \\frac{85.8 - 92.6}{3.6} = -1.89.$\n\n我们可以用 z 统计量来粗略地识别哪些观测比其他观测更异常。\n如果一个观测 $x_1$ 的 z 统计量的绝对值大于另一个观测 $x_2$ 的 z 统计量的绝对值：$|Z_1| > |Z_2|.$，那么就说观测 $x_1$ 比观测 $x_2$ 更异常。当分布是对称的时，这种方法尤其具有启发性。\n\n::: {.guidedpractice data-latex=\"\"}\n在前面的引导练习中，两个刷尾负鼠的观测值，哪一个更*异常*？[^13-foundations-mathematical-6]\n:::\n\n[^13-foundations-mathematical-6]: 因为第二个观测的 z 统计量的*绝对值*大于第一个观测的绝对值，所以第二个观测的头长更异常。\n\n\\vspace{-5mm}\n\n### 正态概率计算\n\n::: {.workedexample data-latex=\"\"}\n在 SAT 引导练习中提到的 Nel，其 SAT 分数为 1800，对应的 $Z=1.$ 他们想知道自己在所有 SAT 考生中处于什么百分位数。\n\n------------------------------------------------------------------------\n\nNel 的**百分位数**\\index{percentile}是指 SAT 分数低于 Nel 的人数百分比。\n我们在 [图 -@fig-satBelow1800]中阴影标出了代表这些人的区域。\n正态曲线下的总面积总是等于 1，而在 SAT 考试中分数低于 Nel 的人的比例，就等于 [图 -@fig-satBelow1800]中阴影区域的*面积*：0.8413。\n换句话说，Nel 位于 SAT 考生的第 $84^{th}$ 百分位数。\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![用于 SAT 分数的正态模型，阴影区域表示分数低于 Nel 的个体。\n](foundations-mathematical_files/figure-pdf/fig-satBelow1800-1.png){#fig-satBelow1800 fig-alt='在均值为 1500、标准差为 300 的正态曲线上标出了 Nel 的 SAT 分数 1800。\n低于 Nel 分数的区域以蓝色阴影显示，约占分布的 84%。\n' width=60%}\n:::\n:::\n\n\n\n\n我们可以使用正态模型来求百分位数或概率。\n一个**标准正态分布表**\\index{normal probability table}列出了 z 统计量及对应的百分位数，可用于根据 z 统计量查找百分位数（反之亦然）。\n统计软件也可用于此目的。\n\n\n\n\n\n\n\n正态概率最常用统计软件来计算，这里我们将用 R 来演示。\n我们用软件来确定与任一特定 z 统计量对应的百分位数。\n例如，$Z=0.43$ 对应的百分位数是 0.6664，即第 $66.64^{th}$ 百分位数。\n`pnorm()` 函数是 R 自带的，它能提供与正态曲线上任意截断点关联的百分位数。\n`normTail()` 函数则来自 [**openintro**](http://openintrostat.github.io/openintro/) R 包，可以绘制相关的正态分布曲线。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(0.43, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.666\n```\n\n\n:::\n\n```{.r .cell-code}\nopenintro::normTail(m = 0, s = 1, L = 0.43)\n```\n\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/unnamed-chunk-12-1.png){width=60%}\n:::\n:::\n\n\n\n\n我们也可以求与某个百分位数对应的 z 统计量。\n例如，要求第 $80^{th}$ 百分位数对应的 z 统计量，我们使用 `qnorm()` 函数，它能根据给定的百分比确定**分位数** (quantile)。分位数代表了截断值。\n（为了记住 `qnorm()` 函数提供截断值（cutoff），可以注意到 `qnorm()` 和 \"cutoff\" 均以 \"kuh\" 音开头。为了记住 `pnorm()` 函数根据给定截断值提供概率（probability），可以注意到 `pnorm()` 和 \"probability\" 均以 \"puh\" 音开头。）我们用 `qnorm()` 来计算第 $80^{th}$ 百分位数对应的 z 统计量：0.84。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.80, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.842\n```\n\n\n:::\n\n```{.r .cell-code}\nopenintro::normTail(m = 0, s = 1, L = 0.842)\n```\n\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/unnamed-chunk-13-1.png){width=60%}\n:::\n:::\n\n\n\n::: {.guidedpractice data-latex=\"\"}\n试确定 SAT 考生中，分数比 Nel 高的考生比例。[^13-foundations-mathematical-7]\n:::\n\n[^13-foundations-mathematical-7]: 如果84%的人得分低于Nel，那么得分更高的人必然占16%。\n    （通常，在使用正态模型或其他任何连续分布时，会忽略同分情况。）\n\n### 正态概率示例\n\nSAT 总分可以用正态模型很好地近似，$N(\\mu=1500, \\sigma=300).$\n\n::: {.workedexample data-latex=\"\"}\nShannon 是一名随机选出的 SAT 考生，我们对 Shannon 的 SAT 能力一无所知。\nShannon 在 SAT 中得分至少为 1630 的概率是多少？\n\n------------------------------------------------------------------------\n\n首先，永远要先绘制并标注正态分布图。\n（图画不需要非常精确，只要能说明问题即可。）我们关心的是其得分高于 1630 的概率，因此将上尾部涂上阴影。\n参见下方的正态曲线。\n\n$x$ 轴标出了均值以及均值上下 2 倍标准差处的值。\n找到曲线下阴影面积最简单的方法是利用临界值的 z 统计量。\n已知 $\\mu=1500,$ $\\sigma=300,$ 以及临界值 $x=1630,$ z 统计量计算如下：\n\n$$ Z = \\frac{x - \\mu}{\\sigma} = \\frac{1630 - 1500}{300} = \\frac{130}{300} = 0.43 $$\n\n我们使用软件来查找 $Z=0.43$ 的百分位数，结果为 0.6664。\n然而，这个百分位数描述的是 z 统计量*低于* 0.43 的人。\n为了求出 $Z=0.43$ *以上*的面积，我们用 1 减去下尾部的面积，如下所示。\n\nShannon 在 SAT 中得分至少为 1630 的概率是 0.3336。\n这一计算过程在 [图 -@fig-subtractingArea]中进行了可视化展示。\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![可视化计算 Shannon 在 SAT 中得分至少为 1630 的概率。\n](foundations-mathematical_files/figure-pdf/fig-subtractingArea-1.png){#fig-subtractingArea fig-alt='三个正态曲线，可视化说明了如何利用面积的算术运算来计算概率。\n1630 以上的面积可以通过用总面积（1）减去 1630 以下的面积（0.6664）来计算。\n最终结果是 0.3336。\n' width=80%}\n:::\n:::\n\n\n::: {.tip data-latex=\"\"}\n**永远先画图，再求 z 统计量。**\n\n对于任何正态概率问题，*永远永远永远*要先绘制并标注正态曲线，并将感兴趣的区域涂上阴影。\n这幅图将提供对该概率的一个估计值。\n\n在画出表示当前情境的图形后，再确定你所关注的观测对应的 z 统计量。\n:::\n\n::: {.guidedpractice data-latex=\"\"}\n如果 Shannon 得分至少为 1630 的概率是 0.3336，那么其得分低于 1630 的概率是多少？\n绘制代表此练习的正态曲线，将下方区域涂上阴影，而不是上方区域。[^13-foundations-mathematical-8]\n:::\n\n[^13-foundations-mathematical-8]: 我们求得的概率为 0.6664。\n    此练习对应的图形由“0.6664”下方的阴影区域表示。\n\n::: {.workedexample data-latex=\"\"}\nEdward 在 SAT 中考了 1400 分。\n其百分位数是多少？\n\n------------------------------------------------------------------------\n\n首先，需要画一张图。\nEdward 的百分位数是指得分未达到 1400 分的人所占的比例。\n这些得分位于 1400 分的左侧，如下图所示。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/edward-percentile-1.png){fig-align='center' fig-alt='一条均值为 1500、标准差为 300 的正态曲线。\n小于 1400 的值在曲线下部被涂成蓝色阴影。\n阴影部分大约占图形的 37%。\n' width=60%}\n:::\n:::\n\n\n利用均值 $\\mu=1500,$ 标准差 $\\sigma=300,$ 以及尾部临界值 $x=1400$ 来计算 z 统计量：\n\n$$ Z = \\frac{x - \\mu}{\\sigma} = \\frac{1400 - 1500}{300} = -0.33$$\n\n可以使用统计软件来求出 $N(0,1)$ 曲线下 $-0.33$ 左侧的面积，结果为 0.3707。\nEdward 处于第 37 百分位数。\n:::\n\n::: {.workedexample data-latex=\"\"}\n利用上一个示例的结果，计算 SAT 考生中成绩比 Edward 好的人所占的比例。\n同时画一张新图。\n\n------------------------------------------------------------------------\n\n如果 Edward 的得分优于 37% 的 SAT 考生，那么大约有 63% 的人得分比他高，如下所示。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/edward-percentile-better-1.png){fig-align='center' fig-alt='一条均值为 1500、标准差为 300 的正态曲线。\n大于 1400 的值在曲线上部被涂成蓝色阴影。\n阴影部分大约占图形的 63%。' width=60%}\n:::\n:::\n\n:::\n\n::: {.tip data-latex=\"\"}\n**右侧面积。**\n\n大多数统计软件以及大多数书中的标准正态分布表，给出的都是左侧面积。\n如果你需要右侧面积，可以先求出左侧面积，然后用 1 减去该值。\n:::\n\n::: {.guidedpractice data-latex=\"\"}\nStuart 的 SAT 成绩为 2100 分。\n为每一小问画一张图。\n(a) 其百分位数是多少？\n(b) 有多少比例的 SAT 考生成绩比 Stuart 好？[^13-foundations-mathematical-9]\n:::\n\n[^13-foundations-mathematical-9]: 数值答案: (a) 0.9772.\n    (b) 0.0228.\n\n基于一个包含 100 名男性的样本，[^13-foundations-mathematical-10]美国 20 至 62 岁之间、性别认同为男性的成年人身高近似服从正态分布，均值为 70.0 英寸，标准差为 3.3 英寸。\n\n[^13-foundations-mathematical-10]: 此样本取自美国农业部食品商品摄入量数据库。\n\n::: {.workedexample data-latex=\"\"}\nKamron 身高 5'7\"（67 英寸），Adrian 身高 6'4\"（76 英寸）。\n(a) Kamron 的身高百分位数是多少？\n(b) Adrian 的身高百分位数是多少？\n同时为每一小问画一张图。\n\n------------------------------------------------------------------------\n\n使用统计软件（例如 R 中的 `pnorm()` 函数）计算得出的数值答案: (a) 第 18.17 百分位数。\n(b) 第 96.55 百分位数。\n:::\n\n前面几个问题都集中在求特定观测的概率或百分位数上。\n如果你想知道对应于某个特定百分位数的观测值是多少呢？\n\n::: {.workedexample data-latex=\"\"}\nYousef（优素福）的身高在第 $40^{th}$ 百分位数。\n他有多高？\n\n------------------------------------------------------------------------\n\n一如既往，第一步是画图。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/unnamed-chunk-14-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n在这种情况下，已知下尾概率为 0.40，可以在图中用阴影表示。\n我们希望找到与已知概率 0.4 相对应的观测。\n我们可以用两种不同的方法找到这个观测：使用上面看到的身高曲线，或者使用与均值为 0、标准差为 1 的标准正态曲线相关的 z 统计量。\n\n如果你有可以指定正态曲线均值和标准差的软件（如下面的 R 代码），就可以直接计算出曲线上的观测（即 Yousef 的身高）。\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 69.2\n```\n\n\n:::\n:::\n\n\nYousef 身高 69.2 英寸。\n也就是说，Yousef 大约 5'9\"（这是 5 英尺 9 英寸的表示法）。\n\n如果没有灵活的软件，你将需要标准正态曲线（均值为 0、标准差为 1 的正态曲线）提供的信息。\n首先，确定与第 $40^{th}$ 百分位数相关的 z 统计量。\n\n因为这个百分位数低于 50%，我们知道 $Z$ 将为负值。\n统计软件给出的 $Z$ 值为 $-0.25.$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.4, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.253\n```\n\n\n:::\n:::\n\n\n已知 $Z_{Yousef}=-0.25$ 以及总体参数 $\\mu=70$ 和 $\\sigma=3.3$ 英寸，我们可以建立 z 统计量公式来确定 Yousef 的未知身高，记为 $x_{Yousef}$：\n\n$$ -0.253 = Z_{Yousef} = \\frac{x_{Yousef} - \\mu}{\\sigma} = \\frac{x_{Yousef} - 70}{3.3} $$\n\n解 $x_{Yousef}$ 得到身高 69.2 英寸。\n再次提醒，Yousef 大约为 5'9\"。\n:::\n\n::: {.workedexample data-latex=\"\"}\n成年男性身高的第 $82^{nd}$ 百分位数是多少？\n\n------------------------------------------------------------------------\n\n为了练习使用 z 统计量，我们将使用标准正态曲线来解决这个问题。\n\n和之前一样，我们先画图。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/height82Perc-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n并计算与第 $82^{nd}$ 百分位数相关的 z 统计量：\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.82, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.915\n```\n\n\n:::\n:::\n\n\n接下来，我们要求第 $82^{nd}$ 百分位数的 z 统计量，它将是一个正值（因为百分位数大于 50%).\n使用 `qnorm()`，第 $82^{nd}$ 百分位数对应于 $Z=0.92.$ 最后，使用 z 统计量公式以及已知的均值 $\\mu$、标准差 $\\sigma$ 和 z 统计量 $Z=0.92$ 来求出身高 $x$：\n\n$$ 0.92 = Z = \\frac{x-\\mu}{\\sigma} = \\frac{x - 70}{3.3} $$\n\n由此得到 73.04 英寸，或者说大约 6'1\"，作为第 $82^{nd}$ 百分位数的身高。\n:::\n\n::: {.guidedpractice data-latex=\"\"}\n使用 z 统计量，回答下列问题。\n\n(a) SAT 分数的第 $95^{th}$ 百分位数是多少？\\\n(b) 男性身高的第 $97.5^{th}$ 百分位数是多少？对于涉及正态概率的问题，请一如既往地先画图。[^13-foundations-mathematical-11]\n:::\n\n[^13-foundations-mathematical-11]: 记住：先画图，再找 z 统计量。\n    （我们把画图留给你自己。） z 统计量可以通过百分位数和标准正态分布表找到。\n    (a) 我们在标准正态分布表的概率部分（中间部分）查找 0.95，这让我们定位到第 1.6 行和（大约）第 0.05 列，即 $Z_{95}=1.65.$ 已知 $Z_{95}=1.65,$ $\\mu = 1500,$ 和 $\\sigma = 300,$ 我们列出 z 统计量公式：$1.65 = \\frac{x_{95} - 1500}{300}.$ 我们求解 $x_{95}$：$x_{95} = 1995.$ (b) 类似地，我们找到 $Z_{97.5} = 1.96,$ 再次为身高列出 z 统计量公式，并计算 $x_{97.5} = 76.5.$\n\n::: {.guidedpractice data-latex=\"\"}\n使用 z 统计量，回答以下问题。\n\n(a) 一名随机选择的成年男性身高至少为 6'2\"（74 英寸）的概率是多少？\\\n(b) 一名成年男性身高低于 5'9\"（69 英寸）的概率是多少？[^13-foundations-mathematical-12]\n:::\n\n[^13-foundations-mathematical-12]: 数值答案： 0.1131.\n    0.3821.\n\n::: {.workedexample data-latex=\"\"}\n一名随机选择的成年男性身高在 5'9\" 到 6'2\" 之间的概率是多少？\n\n------------------------------------------------------------------------\n\n这些身高对应 69 英寸和 74 英寸。\n首先，画出示意图。\n我们感兴趣的区域不再是上尾或下尾。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/unnamed-chunk-18-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n曲线下的总面积为 1。\n如果我们找出两个未涂阴影尾部的面积（根据前一节的引导练习，这两个面积分别是 $0.3821$ 和 $0.1131$），那么我们就可以求出中间区域的面积：\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n也就是说，身高在 5'9\" 到 6'2\" 之间的概率是 0.5048。\n:::\n\n::: {.guidedpractice data-latex=\"\"}\n求出 SAT 考生中得分在 1500 到 2000 之间的百分比。[^13-foundations-mathematical-13]\n:::\n\n[^13-foundations-mathematical-13]: 这是一个简化的解法。\n    （务必画图！）首先找出低于 1500 和高于 2000 的百分比：$Z_{1500} = 0.00 \\to 0.5000$（下方面积），$Z_{2000} = 1.67 \\to 0.0475$（上方面积）。\n    最终答案：$1.0000-0.5000 - 0.0475 = 0.4525.$\n\n::: {.guidedpractice data-latex=\"\"}\n成年男性身高在 5'5\" 到 5'7\" 之间的百分比是多少？[^13-foundations-mathematical-14]\n:::\n\n[^13-foundations-mathematical-14]: 5'5\" 是 65 英寸。\n    5'7\" 是 67 英寸。\n    数值解：$1.000 - 0.0649 - 0.8183 = 0.1168,$ 即 11.68%.\n\n## 量化统计量的变异性\n\n如后续章节所示，许多用于汇总数据的统计量（例如，样本比例、样本均值、两个样本比例之差、两个样本均值之差、线性模型中的样本斜率等），其变异性都符合上文所述的正态分布。\n数学模型源自正态理论，但即使是计算方法（以及这两种方法背后的直觉思维），也利用了前文构建的大多数分布中常见的钟形变异性。\n\n### 68-95-99.7 规则\n\n这里，我们介绍一条实用的通用规则，用于计算正态分布中观测值落在均值 1、2 和 3 个标准差范围内的概率。\n这条规则在实际应用中有广泛的用处，尤其是在没有计算器或 Z 表的情况下进行快速估算时。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![正态分布中，观测值落在均值 1、2 和 3 个标准差范围内的概率。\n](foundations-mathematical_files/figure-pdf/fig-er6895997-1.png){#fig-er6895997 fig-alt='一条正态曲线，显示均值一个标准差范围内的面积（0.68），\n均值两个标准差范围内的面积（0.95），以及均值三个标准差范围内的面积（0.997）。\n' width=60%}\n:::\n:::\n\n\n\n::: {.guidedpractice data-latex=\"\"}\n使用 `pnorm()`（或 Z 表）来确认在正态分布中，大约68%、95%和99.7%的观测值分别落在均值的1、2和3个标准差范围内。\n例如，首先找出落在 $Z=-1$ 和 $Z=1$ 之间的区域面积，其面积应约为 0.68。\n同理，在 $Z=-2$ 和 $Z=2$ 之间的区域面积应约为 0.95。[^13-foundations-mathematical-15]\n:::\n\n[^13-foundations-mathematical-15]: 首先画出图形。\n    要找出 $Z=-1$ 和 $Z=1$ 之间的面积，可使用 `pnorm()` 或标准正态分布表来确定 $Z=-1$ 下方和 $Z=1$ 上方的面积。接着验证 $Z=-1$ 和 $Z=1$ 之间的面积约为 0.68。\n    对 $Z=-2$ 到 $Z=2$ 以及 $Z=-3$ 到 $Z=3$ 的区间重复此操作。\n\n正态随机变量也有可能落在距离均值 4、5 个甚至更多标准差的地方。\n不过，若数据近似正态，这类情况极其罕见。\n距离均值超过 4 个标准差的概率约为 1/30,000。\n对于偏离 5 和 6 个标准差，该概率分别约为 1/350 万和 1/10 亿。\n\n::: {.guidedpractice data-latex=\"\"}\nSAT 分数非常接近正态模型，其均值 $\\mu = 1500$，标准差 $\\sigma = 300.$ 得分在 900 到 2100 分之间的考生百分比大约是多少？\n得分在 1500 到 2100 分之间的百分比是多少？[^13-foundations-mathematical-16]\n:::\n\n[^13-foundations-mathematical-16]: 900 和 2100 分别代表均值上下两个标准差，这意味着大约 95% 的考生得分在 900 到 2100 之间。\n    由于正态模型是对称的，来自 问的一半考生（占所有考生的 $\\frac{95\\%}{2} = 47.5\\%$）将得分在 900 到 1500 分之间，而另外 47.5% 的考生得分在 1500 到 2100 之间。\n\n### 标准误 {#sec-se}\n\n点估计会因样本而异，我们用所谓的**标准误（SE）**\\index{standard error}来量化这种变异性。\n标准误等于与该统计量相联系的标准差。\n所以，举例来说，要量化一个点估计从一个样本到下一个样本的变异性，这种变异性就称为该点估计的标准误。\n几乎在所有情况下，标准误本身也是一个根据样本数据计算得出的估计值。\n\n\n\n\n\n\n\n标准误的确定方法会因具体情形而异。\n不过，通常会使用基于中心极限定理的公式来确定它。\n\n### 误差界 {#sec-moe}\n\n与标准误密切相关的是**误差界**\\index{margin of error}。\n误差界描述观测值与其均值相距多远。例如，为了描述大多数（即95%）观测值所在的范围，我们说误差界约为 $2 \\times SE$。\n也就是说，95%的观测值与均值的距离在两个误差界以内。\n\n::: {.important data-latex=\"\"}\n**样本比例的误差界。**\n\n由 $z^\\star \\times SE$ 给出的距离称为**误差界**\\index{margin of error}。\n\n$z^\\star$ 是正态分布上的截断值。\n$z^\\star$ 最常见的取值是 1.96（通常近似取为 2），这表示误差界描述了 95% 的样本统计量。\n:::\n\n注意，如果观测值的散布范围是从某个下界到某个上界，那么对标准误的一种粗略近似方法是将这个范围除以 4。\n也就是说，如果你注意到样本比例范围是从 0.1 到 0.4，那么标准误可以近似为 0.075。\n\n\n\n\n\n\n\n## 案例研究（检验）：机会成本 {#sec-caseopp}\n\n在推断的语境下使用正态模型的方法，与将模型应用于接近正态的单个观测值的实践非常相似。\n我们将用正态模型来替代之前通过随机化或模拟技术得到的原假设分布，并再次验证结果。\n当样本量足够大时，正态近似通常能得出与模拟模型相同的结论。\n\n### 观测数据\n\n在 [第 -@sec-caseStudyOpportunityCost 节]中，我们介绍了机会成本研究，该研究发现当提醒学生现在不花钱意味着未来可以把钱花在其他事情上时，他们会变得更节俭。\n让我们在正态分布的背景下重新分析这些数据，并比较结果。\n\n::: {.data data-latex=\"\"}\n[`opportunity_cost`](http://openintrostat.github.io/openintro/reference/opportunity_cost.html) 数据集可以在 [**openintro**](http://openintrostat.github.io/openintro) R 包中找到。\n:::\n\n### 统计量的变异性\n\n[图 -@fig-OpportunityCostDiffs-w-normal]总结了利用随机化方法确定的原假设分布。\n拟合该原假设分布最优的正态分布均值为 0。\n我们可以借用我们将在 [第 -@sec-inference-two-props 章]中熟悉的公式来计算该分布的标准误，但这里暂且取给定值 $SE = 0.078$。\n回想一下，差异的点估计值为 0.20，如 [图 -@fig-OpportunityCostDiffs-w-normal]所示。\n接下来，我们将使用正态分布方法来计算 p 值。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![机会成本研究中带有叠加正态曲线的差值原假设分布。此图基于 10,000 次模拟生成。\n](foundations-mathematical_files/figure-pdf/fig-OpportunityCostDiffs-w-normal-1.png){#fig-OpportunityCostDiffs-w-normal fig-alt='机会成本研究中，模拟样本比例差值的直方图上叠加了一条正态曲线。\n理论正态分布与直方图吻合得相当好。\n样本比例的观测差值 0.2 位于正态曲线和直方图的尾部。\n' width=80%}\n:::\n:::\n\n\n\n\n### 观测统计量与原假设统计量\n\n正如我们在 [第 -@sec-normalDist 节]中学到的，绘制正态分布图并涂上阴影会很有帮助，这样我们能确切地知道要计算什么。\n这里我们要找出超出 0.2 的尾部面积，它代表了 p 值。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/OpportunityCostDiffs_normal_only-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n接下来，我们可以利用观测差值 0.20 和两个模型参数来计算 z 统计量。\n标准误 $SE = 0.078,$ 相当于模型的标准差。\n\n$$Z = \\frac{\\text{观测差异} - 0}{SE} = \\frac{0.20 - 0}{0.078} = 2.56$$\n\n我们可以使用统计软件，也可以在标准正态分布表中查找 $Z = 2.56$ 来确定右尾面积：0.0052，这与我们使用随机化方法得到的右尾面积（0.006）大致相同。\n由于 p 值小于 0.05，我们得出结论：处理确实影响了学生的支出。\n\n::: {.important data-latex=\"\"}\n**假设检验中的 z 统计量。**\n\n在假设检验的语境下，点估计的 z 统计量为\n\n$$Z = \\frac{\\text{点估计} - \\text{零值}}{SE}$$\n\n在这种情况下，标准误相当于点估计的标准差，而原假设值来自原假设中的声明。\n:::\n\n我们已经证实，在机会成本案例研究中，之前使用的随机化方法和正态分布方法提供了几乎相同的 p 值和结论。\n接下来，让我们把注意力转向医疗顾问案例研究。\n\n## 案例研究（检验）：医疗顾问 {#sec-casemed}\n\n### 观测数据\n\n在 [第 -@sec-case-study-med-consult 节]中，我们了解到一位医疗顾问报告称，在其 62 位接受肝移植的客户中，只有 3 位出现了并发症，这低于更常见的并发症率 0.10。\n在那部分工作中，我们没有对原假设场景进行建模，但我们将在 [第 -@sec-one-prop-null-boot 节]中讨论一种针对单一比例原假设分布的模拟方法， [图 -@fig-MedConsNullSim-w-normal]提供了这样一个分布。\n我们已在图中添加了拟合最佳的正态曲线，其均值为 0.10。\n借用我们将在 [第 -@sec-inference-one-prop 章]中遇到的公式，我们还计算了该分布的标准误：$SE = 0.038.$\n\n### 统计量的变异性\n\n在开始之前，我们想指出一个容易被忽视的简单细节：我们从模拟生成的原假设分布呈轻微偏态，并且直方图并不特别平滑。\n事实上，正态分布只能说勉强拟合这个模型。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![基于医疗顾问的 10,000 次模拟研究生成的样本比例的原假设分布，\n以及拟合最佳的正态模型。\n](foundations-mathematical_files/figure-pdf/fig-MedConsNullSim-w-normal-1.png){#fig-MedConsNullSim-w-normal fig-alt='正态曲线叠加在医疗顾问研究的模拟样本比例的直方图上。\n由于样本比例分布的偏态，理论正态分布对直方图的拟合情况\n不如 [图 -@fig-OpportunityCostDiffs-w-normal]中那样好。\n观测到的样本比例 0.0484 在正态曲线和直方图中都处于尾部，\n但它不是一个极端值。\n' width=80%}\n:::\n:::\n\n\n\n\n### 观测统计量与原假设统计量\n\n像往常一样，在计算正态概率之前，我们先画个图。\n下图是一个以 0.10 为中心、标准误为 0.038 的正态分布。\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](foundations-mathematical_files/figure-pdf/MedConsNullSim-normal-only-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n接下来，我们可以使用观测到的并发症率 $\\hat{p} = 0.048$ 以及正态模型的均值和标准差来计算 z 统计量。\n这里我们再次使用标准误作为标准差。\n\n$$Z = \\frac{\\hat{p} - p_0}{SE_{\\hat{p}}} = \\frac{0.048 - 0.10}{0.038} = -1.37$$\n\n通过统计软件或标准正态分布表确定 $Z = -1.37$，我们可以得出左侧尾部面积为 0.0853，这就是该假设检验的估计 p 值。\n这里有一个小问题：p 值 0.0853 几乎比 [第 -@sec-one-prop-null-boot 节]中将要计算的模拟 p 值 0.1222 小了 30%。\n\n这种差异可以解释为正态模型在 [图 -@fig-MedConsNullSim-w-normal]中对原假设分布的近似效果不佳。\n如前所述，模拟得到的原假设分布不是很平滑，而且分布本身呈轻微偏态。\n这是坏消息。\n好消息是，我们可以通过一些简单的检查来预见这些问题。\n我们将在接下来的章节中了解更多关于这些检查的内容。\n\n在 [第 -@sec-CLTsection 节]中我们指出，应用中心极限定理的两个常见条件是：(1) 样本中的观测必须是独立的，(2) 样本量必须足够大。\n针对这一特定情况的指南——我们将在 [第 -@sec-inference-one-prop 章]中学习——本应提醒我们正态模型的近似效果不佳。\n\n### 应用正态模型的条件\n\n本节的成功案例是在机会成本数据中应用了正态模型。\n然而，最大的教训来自于在医疗顾问案例研究中使用正态近似的尝试不太成功。\n\n统计技术就像木匠的工具。\n如果负责任地使用，它们可以产生出色而精确的结果。\n然而，如果工具被不负责任地使用或在不适当的条件下应用，就会产生不可靠的结果。\n因此，在后续章节介绍每一种统计方法时，我们都将仔细概述可以合理使用该方法的条件。\n在每次应用该技术时，都应该检查这些条件。\n\n在学完本课程的入门主题之后，进阶学习可能会涉及使用复杂的模型，例如将多个具有不同变异结构的变量结合在一起进行分析。\n处理来自正态总体的数据会使高阶模型的估计和解释更加容易。\n有时，模拟、随机化或自助法在结构或计算需求上会显得难以处理。\n正态性通常允许我们使用简单直接的建模技术对数据进行极佳的近似。\n\n## 案例研究（区间估计）：支架 {#sec-casestent}\n\n点估计是我们对参数值的最佳猜测，因此围绕该值构建置信区间是合理的。标准误衡量与点估计相关的不确定性，它为我们应该构建多大的置信区间提供了指导。68-95-99.7法则告诉我们，通常有 95% 的观测值落在均值 2 个标准误范围内。\n这里，我们使用1.96这个值是为了更精确一些。\n\n::: {.important data-latex=\"\"}\n**构造 95% 置信区间。**\n\n当一个点估计的抽样分布可以合理地用正态模型建模时，我们观测到的点估计与感兴趣的参数真值的距离在1.96个标准误以内的情况约占95%。\n因此，可以为此类点估计构造**95%置信区间**\\index{95\\% confidence interval}\\index{confidence interval}：\n\n\\vspace{-5mm}\n\n$$\\text{点估计} \\pm 1.96 \\times SE$$\n\n我们可以**有 95% 的置信度**\\index{95\\% confident}认为该区间捕获了真参数值。\n:::\n\n\\vspace{-3mm}\n\n\n\n\n\n\n::: {.guidedpractice data-latex=\"\"}\n计算均值为0、标准差为1的正态分布在 -1.96 和 1.96 之间的面积。[^13-foundations-mathematical-17]\n:::\n\n[^13-foundations-mathematical-17]: 我们留给你来画图。\n    z 统计量为 $Z_{left} = -1.96$ 和 $Z_{right} = 1.96$。这两个 z 统计量之间的面积是 $0.9750 - 0.0250 = 0.9500$。这就是 95% 置信区间公式中“1.96”这个数值的由来。\n\n::: {.workedexample data-latex=\"\"}\n机会成本研究中的点估计为：如果提醒学生现在不花的钱以后可以花在其他东西上，购买视频的学生会减少20%。\n该点估计可以用一个标准误为 $SE = 0.078$ 的正态分布合理建模。为该点估计构造一个95%置信区间。\n\n------------------------------------------------------------------------\n\n由于已知该点估计可以用正态分布建模：\n\n\\vspace{-5mm}\n\n$$\\text{点估计} \\pm 1.96 \\times SE = 0.20 \\pm 1.96 \\times 0.078 = (0.047, 0.353)$$\n\n我们有95%的置信度认为，处理组的视频购买率比对照组低4.7%至35.3%。\n由于该置信区间不包含0，它与我们之前拒绝\"无差异\"这一说法的假设检验结果是一致的。\n\n请注意，我们使用了上一节中的 $SE = 0.078$。\n然而，更一般的做法是使用样本比例，以略微不同的方式重新计算此置信区间的标准误。\n目前无需担心这个细节，因为在此案例中，两种方法得到的标准误几乎相同。\n:::\n\n### 观测数据\n\n考虑一项检验对中风高危患者大脑植入支架是否有助于降低中风风险的实验。\n这项研究前30天的结果汇总在 [表 -@tbl-stentStudyResultsCIsection]中，该研究共包括451名患者。\n这些结果令人惊讶！\n点估计表明，接受支架的患者可能有*更高的*中风风险：$p_{trmt} - p_{ctrl} = 0.090.$\n\n\n::: {#tbl-stentStudyResultsCIsection .cell tbl-cap='支架研究30天结果的描述性统计。' tbl-pos='H'}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{>{\\raggedright\\arraybackslash}p{7em}>{\\raggedleft\\arraybackslash}p{7em}>{\\raggedleft\\arraybackslash}p{7em}>{\\raggedleft\\arraybackslash}p{7em}}\n\\toprule\n组别 & 无事件 & 中风 & 总计\\\\\n\\midrule\n\\cellcolor{gray!10}{control} & \\cellcolor{gray!10}{214} & \\cellcolor{gray!10}{13} & \\cellcolor{gray!10}{227}\\\\\ntreatment & 191 & 33 & 224\\\\\n\\cellcolor{gray!10}{Total} & \\cellcolor{gray!10}{405} & \\cellcolor{gray!10}{46} & \\cellcolor{gray!10}{451}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n::: {.data data-latex=\"\"}\n[`stent30`](http://openintrostat.github.io/openintro/reference/stent30.html) 数据可以在 [**openintro**](http://openintrostat.github.io/openintro) R 包中找到。\n:::\n\n### 统计量的变异性\n\n::: {.workedexample data-latex=\"\"}\n考虑支架研究及其结果。\n保证点估计 $p_{trmt} - p_{ctrl} = 0.090$ 近似正态的必要条件已为您验证，该估计量的标准误为 $SE = 0.028$。为使用支架导致的30天中风率变化构造一个95%置信区间。\n\n------------------------------------------------------------------------\n\n应用正态模型的条件已验证，因此我们可以继续构建置信区间：\n\n$$\\text{点估计} \\pm 1.96 \\times SE = 0.090 \\pm 1.96 \\times 0.028 = (0.035, 0.145)$$\n\n我们有95%的置信度认为，在脑中风患者脑部植入支架会使30天内的中风风险增加0.035至0.145。\n此置信区间也可以以一种类似于假设检验的方式使用：由于区间不包含0（完全在0以上），这意味着数据提供了有说服力的证据，表明研究中使用的支架改变了30天内的中风风险。\n:::\n\n与假设检验一样，置信区间也不是完美的。约有1/20正确构建的95%置信区间会因观测数据的自然变异性而未能包含感兴趣的参数。\n[图 -@fig-95PercentConfidenceInterval]展示了针对一个比例构建的 25 个置信区间，这些区间基于 25 个不同的数据集构建，且这些数据集均来自同一个真实比例为 $p = 0.3$ 的总体。然而，这 25 个置信区间中恰有 1 个未能包含真实值。\n\n未能捕捉到 $p=0.3$ 的区间并不是由于糟糕的科学实践造成的。相反，它是由于自然变异性引起的，并且我们应该*预期*我们的一些区间会错过感兴趣的参数。事实上，在一生中创建 95% 置信区间时，你应该预期你报告的区间中有 5% 会错过感兴趣的参数（不幸的是，你永远不知道你报告的哪些区间捕获了参数，哪些错过了参数）。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![从一个 $p = 0.30$ 的总体中收集了 25 个大小为 $n=300$ 的样本。针对每个样本，\n都创建了一个置信区间以尝试捕捉真实比例 $p$。然而，这 25 个区间中有 1 个未能捕捉到 $p = 0.30$。\n](foundations-mathematical_files/figure-pdf/fig-95PercentConfidenceInterval-1.png){#fig-95PercentConfidenceInterval fig-alt='绘制了一系列 25 条水平线，代表 25 个不同的样本。每条垂直的线段的起点是其对应样本所构建\n的置信区间的下限值，终点是其上限值。线段中央的实心圆点表示该特定样本中观测到的成功比例。\n一条垂直的虚线穿过这些水平线，位于 p = 0.3 处（这是总体比例的真实值）。25 条水平线中有\n24 条与位于 0.3 处的垂直线相交，但有一条水平线完全低于 0.3。那条未与 0.3 相交的线被标为红色，\n因为来自该特定样本的置信区间未能捕捉到真实的总体比例。' width=80%}\n:::\n:::\n\n\n\n::: {.guidedpractice data-latex=\"\"}\n在 [图 -@fig-95PercentConfidenceInterval]中，有一个区间没有包含真实比例 $p = 0.3$。这是否意味着被选中的数据集存在问题？[^13-foundations-mathematical-18]\n:::\n\n[^13-foundations-mathematical-18]: 不是的。正如有些观测值会落在距离均值超过 1.96 个标准差的地方一样，有些点估计也会落在距离参数超过 1.96 个标准误的地方。置信区间只为参数提供一个合理的取值范围。虽然基于数据我们可能会说其他取值是不太合理的，但这并不意味着它们是不可能的。\n\n### 解释置信区间\n\n细心的读者可能已经注意到，用于描述置信区间的语言略显生硬。\n\n::: {.important data-latex=\"\"}\n**正确的置信区间解释。**\n\n我们有XX%的置信度认为总体参数介于*下限*和*上限*之间（其中*下限*和*上限*均为数值）。\n\n**错误的**说法可能会试图将置信区间描述为以一定的概率捕捉总体参数。\n\n这是最常见的错误之一：尽管将其看作概率可能对理解有用，但置信水平仅仅量化了参数位于该区间内的合理性。\n:::\n\n关于置信区间另一个特别重要的考量是，它们*只试图捕捉总体参数*。我们的区间无法说明捕捉个体观测、一部分观测或点估计的置信度。置信区间提供区间估计，并试图捕捉**总体参数**。\n\n\\index{confidence interval}\n\n\\clearpage\n\n## 章节回顾 {#sec-chp13-review}\n\n### 小结\n\n我们可以将使用正态模型的过程总结如下：\n\n-   **构建研究问题。** 数学模型可同时应用于假设检验与置信区间框架。请确保你选用的推断方法最适合解决你的研究问题。\n-   **通过观察性研究或实验收集数据。** 为解决研究问题，收集感兴趣变量的数据。注意，你的数据可能是来自总体的随机样本，也可能是随机化实验的一部分。\n-   **为统计量的随机性建模。** 在许多情况下，正态分布将是描述与感兴趣的统计量相关的随机性的优秀模型。中心极限定理告诉我们，如果样本量足够大，在描述统计量如何随样本的不同而变化时，样本平均数（可表现为比例或样本均值）将近似服从正态分布。\n-   **计算统计量的变异性。** 使用公式，计算得出统计量的标准差（或更常见的是，称为标准误的标准差估计值）。统计量的标准误将提供信息，表明观察到的统计量距离原假设值（若进行假设检验）或未知的总体参数（若构建置信区间）有多远。\n-   **使用正态分布量化变异性。** 正态分布将提供一个概率，用于度量观察到的统计量与假设的参数（或观察到的统计量与未知的参数）相差到所测得程度的可能性。这种差异的罕见（或不罕见）程度将构成研究问题的结论。\n-   **得出结论。** 利用分析得到的 p 值或置信区间，对感兴趣的研究问题作出报告。同时，务必用平实的语言写下结论，以便普通读者也能理解结果。\n\n[表 -@tbl-chp13-summary]是对推断的数学模型方法的又一次审视。\n\n\n::: {#tbl-chp13-summary .cell tbl-cap='数学模型作为推断统计方法的总结。' tbl-pos='H'}\n::: {.cell-output-display}\n\n\\begin{tabu} to \\linewidth {>{\\raggedright\\arraybackslash}p{15em}>{\\raggedright}X}\n\\toprule\n问题 & 答案\\\\\n\\midrule\n\\cellcolor{gray!10}{它做什么？} & \\cellcolor{gray!10}{运用理论（主要是中心极限定理）描述重复随机化实验或随机抽样产生的假想变异性}\\\\\n\\addlinespace\n所描述的随机过程是什么？ & 随机化实验或随机抽样\\\\\n\\addlinespace\n\\cellcolor{gray!10}{还能近似哪些随机过程？} & \\cellcolor{gray!10}{也可描述观察性模型中的随机抽样或实验中的随机分配}\\\\\n\\addlinespace\n最适合用于什么？ & 快速分析，例如计算 z 统计量\\\\\n\\addlinespace\n\\cellcolor{gray!10}{什么实物可以表示模拟过程？} & \\cellcolor{gray!10}{不适用}\\\\\n\\addlinespace\n需要哪些技术条件？ & 独立性、大样本量\\\\\n\\bottomrule\n\\end{tabu}\n\n\n:::\n:::\n\n\n\n\n\\clearpage\n\n### 术语\n\n本章引入的术语如 [表 -@tbl-terms-chp-13]所示。\n如果你不确定其中某些术语的含义，我们建议你回到正文中回顾其定义。\n你应该能轻松地将它们识别为**粗体文本**。\n\n\n::: {#tbl-terms-chp-13 .cell tbl-cap='本章引入的术语。' tbl-pos='H'}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{>{\\raggedright\\arraybackslash}p{12em}>{\\raggedright\\arraybackslash}p{12em}>{\\raggedright\\arraybackslash}p{12em}}\n\\toprule\n\\cellcolor{gray!10}{95\\% 置信区间} & \\cellcolor{gray!10}{正态分布} & \\cellcolor{gray!10}{百分位数}\\\\\n置信度为 95\\% & 正态模型 & 抽样分布\\\\\n\\cellcolor{gray!10}{中心极限定理} & \\cellcolor{gray!10}{标准正态分布表} & \\cellcolor{gray!10}{标准误}\\\\\n误差界 & 原假设分布 & 标准正态分布\\\\\n\\cellcolor{gray!10}{正态曲线} & \\cellcolor{gray!10}{参数} & \\cellcolor{gray!10}{z 统计量}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n\n\\clearpage\n\n## 练习题 {#sec-chp13-exercises}\n\n奇数号练习题的答案可在 [附录 -@sec-exercise-solutions-13]中找到。\n\n::: {.exercises data-latex=\"\"}\n1.  **曲线下面积，第一部分。** 在标准正态分布 $N(\\mu=0, \\sigma=1)$ 中，由以下 $Z$ 不等式表示的每个区域所占的百分比是多少？\n    务必画出图形。\n    在上文中，我们使用 R 计算了正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    a.  $Z < -1.35$\n\n    b.  $Z > 1.48$\n\n    c.  $-0.4 < Z < 1.5$\n\n    d.  $|Z| > 2$\n\n\\vfill\n\n2.  **曲线下面积，第二部分。** 在标准正态分布 $N(\\mu=0, \\sigma=1)$ 中，由以下 $Z$ 不等式表示的每个区域所占的百分比是多少？\n    务必画出图形。\n    在上文中，我们使用 R 计算了正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    a.  $Z > -1.13$\n\n    b.  $Z < 0.18$\n\n    c.  $Z > 8$\n\n    d.  $|Z| < 0.5$\n\n\\vfill\n\n3.  **GRE 成绩，z 统计量。** Sophia 参加了研究生入学考试（GRE），在文字推理部分得了 160 分，在定量推理部分得了 157 分。\n    所有考生的文字推理部分均值为 151 分，标准差为 7；定量推理部分均值为 153 分，标准差为 7.67。\n    假设两个分布都近似正态。\n    利用上述信息计算下列各项。\n    在上文中，我们使用 R 计算了正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    a.  写出这两个正态分布的简记方式。\n\n    b.  Sophia 在文字推理部分的 z 统计量是多少？在定量推理部分的 z 统计量是多少？\n        画一个标准正态分布曲线，并标出这两个 z 统计量。\n\n    c.  这些 z 统计量告诉了你什么信息？\n\n    d.  相对于其他人，Sophia 在哪一部分表现得更好？\n\n    e.  分别找出她在这两次考试中的百分位数。\n\n    f.  在文字推理部分，有多少百分比的考生比她表现更好？\n        在定量推理部分呢？\n\n    g.  解释为什么简单地比较这两个部分的原始分数，可能会在判断学生哪一部分表现更好时得出错误结论。\n\n    h.  如果这些考试的分数分布不是近似正态的，你对 部分的答案会改变吗？\n        解释你的推理。\n\n\\vfill\n\n\\clearpage\n\n4.  **铁人三项时间，z 统计量。** 在铁人三项比赛中，选手通常被编入不同的年龄和性别组。\n    两位朋友，Leo 和 Mary，都完成了埃尔莫萨海滩铁人三项赛，Leo 在“男性，30-34 岁”组别比赛，Mary 在“女性，25-29 岁”组别比赛。\n    Leo 以 1:22:28（4948 秒）完成比赛，而 Mary 以 1:31:53（5513 秒）完成。\n    我们可以看到 Leo 完成得更快，但他们很好奇自己在各自组别内的表现如何。\n    你能帮助他们吗？\n    以下是关于他们组别表现的一些信息。\n    利用这些信息计算下列各项。\n    在上文中，我们使用 R 计算了正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    \\vspace{-1mm}\n\n    -   “男性，30-34 岁”组的完赛时间均值为 4313 秒，标准差为 583 秒。\n\n    -   “女性，25-29 岁”组的完赛时间均值为 5261 秒，标准差为 807 秒。\n\n    -   两个组的完赛时间分布都近似正态。\\\n        请记住：更好的表现对应着更快的完赛时间。\n\n    a.  写出这两个正态分布的简记方式。\n\n    b.  Leo 和 Mary 的完赛时间的 z 统计量各是多少？\n        这些 z 统计量告诉了你什么？\n\n    c.  Leo 和 Mary 谁在自己的组别中排名更靠前？\n        解释你的推理。\n\n    d.  Leo 比其所在组别中百分之多少的铁人三项选手完成得更快？\n\n    e.  Mary 比其所在组别中百分之多少的铁人三项选手完成得更快？\n\n    f.  如果完赛时间的分布不是近似正态的，你对 部分的答案会改变吗？\n        解释你的推理。\n\n\\vfill\n\n5.  **GRE 分数，临界值。** 考虑之前提到的两个 GRE 分数分布：考试的文字推理部分为 $N(\\mu=151, \\sigma=7)$，定量推理部分为 $N(\\mu=153, \\sigma=7.67)$。\n    利用该信息计算下列各项。\n    在上文中，我们使用了 R 来计算正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    a.  一名在定量推理部分得分处于第 $80^{th}$ 百分位数的学生的分数。\n\n    b.  一名在言语推理部分得分比 70% 的考生差的学生的分数。\n\n\\vfill\n\n6.  **铁人三项时间，临界值。** 回顾两个不同的铁人三项时间分布：“男性，30-34 岁”组为 $N(\\mu=4313, \\sigma=583)$，“女性，25-29 岁”组为 $N(\\mu=5261, \\sigma=807)$。\n    时间以秒为单位列出。\n    利用该信息计算下列各项。\n    在上文中，我们使用了 R 来计算正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    a.  男子组中最快的 5% 运动员（即完成时间最短的 5% 的运动员）的临界时间。\n\n    b.  女性组中最慢的 10% 运动员的临界时间\n\n\\vfill\n\n7.  **洛杉矶天气，华氏度。** 洛杉矶六月的日最高气温的平均数为 77$^\\circ$ F，标准差为 5$^\\circ$ F。\n    假设六月的温度紧密服从正态分布。\n    利用该信息计算下列各项。\n    在上文中，我们使用了 R 来计算正态概率。\n    你也可以选择使用其他来源，例如 [Shiny App](https://openintro.shinyapps.io/dist_calc/) 或正态分布表。\n\n    a.  在六月随机选择的一天，在洛杉矶观测到 83$^\\circ$ F 或更高温度的概率是多少？\n\n    b.  洛杉矶六月份最冷的 10% 的日子（最高温度最低的日子）有多冷？\n\n\\vfill\n\n\\clearpage\n\n8.  **CAPM。** 资本资产定价模型（CAPM）是一个假设投资组合收益率服从正态分布的金融模型。\n    假设一个投资组合的平均年收益率为 14.7%（即平均收益为 14.7%），标准差为 33%。收益率为 0% 意味着投资组合的价值没有变化，负收益率意味着投资组合亏损，而正收益率意味着投资组合盈利。\n\n    a.  该投资组合在百分之多少的年份会亏损，即收益率小于 0%?\n\n    b.  该投资组合年回报率最高的 15% 的临界值\n\n\\vfill\n\n9.  **洛杉矶天气，摄氏度。** 回顾之前的设定：洛杉矶六月的日最高气温的平均数为 77$^\\circ$ F，标准差为 5$^\\circ$ F，并且可以假设最高气温服从正态分布。\n    我们使用以下公式将 $^\\circ$F（华氏度）转换为 $^\\circ$C（摄氏度）：$C = (F - 32) \\times \\frac{5}{9}.$\n\n    a.  写出洛杉矶六月温度（以 $^\\circ$C 为单位）分布的概率模型。\n\n    b.  在洛杉矶的六月，观测到 28$^\\circ$ C（大约对应 83$^\\circ$ F）或更高温度的概率是多少？\n        使用 部分中的 $^\\circ$C 模型计算。\n\n    c.  在本问题的 部分和上一个关于洛杉矶天气问题的 部分中，你得到的是相同还是不同的答案？\n        你感到惊讶吗？\n        请解释。\n\n    d.  估计洛杉矶六月温度（以 $^\\circ$C 为单位）的四分位距（IQR）。\n\n\\vfill\n\n10. **求标准差。** 在以下情况下求分布的标准差。\n\n    a.  MENSA 是一个其成员 IQ 处于人群最高 2% 的组织。\n        IQ 服从均值为 100 的正态分布，加入 MENSA 所需的最低 IQ 分数为 132。\n\n    b.  20 至 34 岁女性的胆固醇水平近似服从正态分布，均值为 185 毫克每分升。\n        胆固醇水平高于 220 mg/dl 的女性被认为患有高胆固醇，约有 18.5% 的女性属于这一类别。\n\n\\vfill\n\n11. **慢性疾病。** 2013 年，Pew Research Foundation 报告称“45% 的美国成年人报告称他们患有一种或多种慢性疾病”。\n    然而，该值基于样本，因此其本身可能不是对感兴趣的总体参数的完美估计。\n    研究报告的标准误约为 1.2%，并且在此情况下可以合理地使用正态模型。\n\n    a.  创建一个患有一种或多种慢性疾病的美国成年人比例的 95% 置信区间。\n        同时，在研究背景下解释该置信区间。\n        [@data:pewdiagnosis:2013]\n\n    b.  判断以下每个陈述的真假。\n        给出解释来论证你的每个答案。\n\n        i.  我们可以肯定地说， 部分中的置信区间包含了患有慢性疾病的美国成年人真实百分比。\n\n        ii. 如果我们重复这项研究 1000 次，并为每次研究构建一个 95% 置信区间，那么这些置信区间中大约有 950 个将包含患有慢性疾病的美国成年人的真实比例。\n\n        iii. 该调查提供了统计上可辨识的证据（在 $\\alpha = 0.05$ 水平上），表明患有慢性疾病的美国成年人百分比低于 50%.\n\n        iv. 由于标准误是 1.2%，研究中只有 1.2% 的人对自己的答案表达了不确定性。\n\n\\vfill\n\n\\clearpage\n\n12. **社交媒体用户与新闻，数学模型。** 2022年进行的一项调查发现，50% 的美国成年人（即比例为 0.5）有时或经常从社交媒体获取新闻。\n    该估计值的标准误为 0.5%（即 0.005），并且可以使用正态分布对样本比例进行建模。\n    [@data:socialmedianews:2022]\n\n    a.  构造一个有时或经常在社交媒体上获取新闻的美国成年人比例的 99% 置信区间，并在问题背景下解释该置信区间。\n\n    b.  判断以下每个陈述是对还是错。\n        请给出解释来论证你的每个答案。\n\n        i.  这些数据提供了统计上可辨识的证据，表明超过一半的美国成年用户有时或经常通过社交媒体获取新闻。\n            使用可辨识水平 $\\alpha = 0.01$。\n\n        ii. 由于标准误是 0.5%，我们可以得出结论，所有美国成年用户中有 99.5% 被纳入了这项研究。\n\n        iii.如果我们想降低估计值的标准误，我们应该收集更少的数据。\n\n        iv. 如果我们为有时或经常通过社交媒体获取新闻的美国成年人百分比构造一个 90% 置信区间，所得的置信区间将比相应的 99% 置信区间更宽。\n\n\\vfill\n\n13. **解读来自样本比例的 z 统计量。** 假设你对一个总体比例进行假设检验，并计算出 z 统计量为 0.47。\n    以下哪一项是对该值的最佳解释？\n    对于不是最佳解释的选项，指出它们所描述的统计概念。[^_13-ex-foundations-mathematical-1]\n\n    a.  原假设为真的概率是 0.47。\n\n    b.  如果原假设为真，那么获得一个与总体比例的假设值相差如观测值那样远的样本比例的概率将是 0.47。\n\n    c.  样本比例比总体比例的假设值大 0.47 个标准误。\n\n    d.  样本比例等于 0.47 乘以标准误。\n\n    e.  样本比例距离总体的假设值 0.47。\n\n    f.  样本比例是 0.47。\n\n\\vfill\n\n14. **心理健康。** 综合社会调查提出了一个问题：“在过去 30 天里，有多少天你的心理健康（包括压力、抑郁和情绪问题）不好？” 基于 1,151 名美国居民的回复，该调查报告了 2010 年的 95% 置信区间为 3.40 至 4.24 天。\n\n    a.  结合数据背景解释这个区间。\n\n    b.  “95% confident\" mean?” 是什么意思？\n        结合应用背景进行解释。\n\n    c.  假设研究人员认为 99% 的置信水平更适合这个区间。\n        这个新区间会比 95% 的置信区间更宽吗？\n\n    d.  如果要对 500 名美国人进行一项新调查，你认为估计值的标准误会变大、变小，还是大致相同？\n\n\\vfill\n\n\\clearpage\n\n15. **重复水样检测。** 一个非营利组织想了解饮用水中铅含量超标的家庭比例。\n    他们预计至少 5% 的家庭铅含量超标，但不超过约 30%。\n    他们随机抽取 800 户家庭，与房主合作获取水样，然后计算这些家庭中铅含量超标的比例。\n    他们重复此过程 1,000 次，并构建一个样本比例的分布。\n\n    a.  这个分布叫什么？\n\n    b.  你预期这个分布的形状是对称的、右偏的还是左偏的？\n        解释你的理由。\n\n    c.  这个分布的变异性叫什么名字？\n\n    d.  假设研究人员的预算缩减，他们每个样本只能收集 250 个观测，但他们仍然可以收集 1,000 个样本。\n        他们构建了一个新的样本比例分布。\n        这个新分布的变异性与每个样本包含 800 个观测时的分布变异性相比如何？\n\n\\vspace{10mm}\n\n16. **重复学生样本。** 在一所大型学院的所有新生中，16% 的学生在本年度入选了院长名单。\n    作为一个课堂项目的一部分，学生们随机抽取 40 名学生，并检查这些学生是否在名单上。\n    他们重复此过程 1,000 次，并构建一个样本比例的分布。\n\n    a.  这个分布叫什么？\n\n    b.  你预期这个分布的形状是对称的、右偏的还是左偏的？\n        解释你的理由。\n\n    c.  这个分布的变异性叫什么名字？\n\n    d.  假设学生们决定再次抽样，这次每个样本收集 90 名学生，并且他们再次收集了 1,000 个样本。\n        他们构建了一个新的样本比例分布。\n        这个新分布的变异性与每个样本包含 40 个观测时的分布变异性相比如何？\n\n[^_13-ex-foundations-mathematical-1]: 本题的灵感来自 Allan Rossman 博士的博客 [Ask Good Questions](https://askgoodquestions.blog/) 上的讨论。\n\n\n:::\n",
    "supporting": [
      "foundations-mathematical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}