1.  \(a\) 正关联：孕期较长的哺乳动物往往寿命也更长。 关联仍为正关联。 否，它们不是独立的。参见 部分。

    \addtocounter{enumi}{1}

1.  下图显示了一个加速增长期。在培养皿大小成为减缓生长的因素之前，开始阶段可能还有一段指数增长期。

    ```{r}
    #| out-width: 30%
    set.seed(2406)
    par(mar = c(1.5, 1.5, 0.5, 0.5), mgp = c(0.3, 0.7, 0),  mfrow = c(1,1), cex.lab = 1.5)
    curve(-1*dexp(x, rate = 4), lwd = 2, xlab = "时间", ylab = "细菌细胞数量", axes = FALSE)
    box()
    ```

    \addtocounter{enumi}{1}

1.  \(a\) 下降：新分数低于先前 24 个分数的均值。 计算加权均值。对旧均值使用权重 24，对新均值使用权重 1：$(24\times 74 + 1\times64)/(24+1) = 73.6$。 新分数偏离先前均值超过 1 个标准差，所以增加。

    \addtocounter{enumi}{1}

1.  任何平均休假天数介于该厂全体员工休假天数的最小值与均值之间的 10 名员工。

    \addtocounter{enumi}{1}

1.  \(a\) 分布 B 的均值更高，因为 $20 > 13$；标准差也更高，因为 20 比 13 离其余数据更远。 分布 A 的均值更高，因为 $-20 > -40$；分布 B 的标准差更高，因为 -40 比 -20 离其余数据更远。 分布 B 的均值更高，因为该分布中的所有值都高于分布 A 中的值；但两个分布具有相同的标准差，因为它们围绕各自均值的变异性相同。 两个分布的均值相同，因为均以 300 为中心；但分布 B 的标准差更高，因为其观测值比分布 A 中的观测值离均值更远。

    \addtocounter{enumi}{1}

1.  \(a\) 大约 26。 由于分布是右偏的，均值高于中位数。 Q1：介于 15 和 20 之间，Q3：介于 35 和 40 之间，IQR：大约 20。 被视为异常低或异常高的值，是指偏离四分位数超过 1.5$\times$IQR 的值。上围栏：Q3 + 1.5 $\times$ IQR = $37.5 + 1.5 \times 20 = 67.5$；下围栏：Q1 - 1.5 $\times$ IQR = $17.5 + 1.5 \times 20 =  -12.5$；记录的最低 AQI 不低于 5，最高 AQI 不高于 65，二者均在围栏之内。因此，本样本中没有哪一天会被认为具有异常低或异常高的 AQI。

    \addtocounter{enumi}{1}

1.  直方图显示该分布是双峰的，这在箱线图中并不明显。箱线图使我们更容易识别须之外的观测值的更精确数值。

    \addtocounter{enumi}{1}

1.  \(a\) 右偏的，存在一个自然边界 0，并且只有少数人拥有许多宠物。中心：中位数，变异性：IQR。 右偏的，存在一个自然边界 0，并且只有少数人居住地离工作地点非常远。中心：中位数，变异性：IQR。 对称。中心：均值，变异性：标准差。 左偏的。中心：中位数，变异性：IQR。 左偏的。中心：中位数，变异性：IQR。

    \addtocounter{enumi}{1}

1.  否，我们预期该分布是右偏的。原因有二：存在一个自然边界 0（看电视的时间不可能少于 0 小时），并且该分布的标准差相对于均值非常大。

    \addtocounter{enumi}{1}

1.  否，离群值很可能是分布的最大值和最小值，因此基于这些值的统计量不可能对离群值具有稳健性。

    \addtocounter{enumi}{1}

1.  第 75 百分位数是 82.5，所以将有 5 名学生获得 A。另外，根据定义，25% 的学生将高于第 75 百分位数。

    \addtocounter{enumi}{1}

1.  \(a\) 如果 $\frac{\bar{x}}{median} = 1$，则 $\bar{x} = 中位数$。这最可能发生在对称分布中。 如果 $\frac{\bar{x}}{median} < 1$，则 $\bar{x} < 中位数$。这最可能发生在左偏的分布中，因为均值比中位数更容易受到较小值的影响（从而被拉低）。 如果 $\frac{\bar{x}}{median} > 1$，则 $\bar{x} > 中位数$。这最可能发生在右偏的分布中，因为均值比中位数更容易受到较大值的影响（从而被拉高）。

    \addtocounter{enumi}{1}

1.  \(a\) 西班牙裔人口百分比的分布极度右偏，大多数县的西班牙裔居民比例低于 10%。然而，有少数县的西班牙裔人口比例超过 90%。在某些分析中，使用对数转换后的值可能更可取，因为该分布的偏态会大大减弱。 地图显示，西班牙裔居民比例较高的县集中在西南边境、整个新墨西哥州、得克萨斯州西南部的大片区域、加利福尼亚州南部的三分之二区域以及南佛罗里达州。在地图中，所有西班牙裔居民比例超过 40% 的县都由较深的阴影表示，因此无法辨别西班牙裔比例究竟有多高。直方图显示有些县的西班牙裔居民比例超过 90%。直方图还可用于估计中心度量和离散度。 两种可视化方法都很有用，但如果只能检查一种，我们应该检查地图，因为它明确地将地理数据与每个县的比例联系在一起。
\addtocounter{enumi}{1}

    \addtocounter{enumi}{1}